version: '3.7'


volumes:
  msdata:


services:

  django:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: django
    env_file:
      - docker/env/.env.dev
    volumes:
      - ./:/app
      - ./media:/app/media
    depends_on:
      - dbmysql
      - redis
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py loaddata db.json &&
                    python3 manage.py runserver 0.0.0.0:8000"

  dbmysql:
    image: mysql:8
    container_name: dbmysql
    ports:
      - "3308:3306"
    environment:
      - TZ=Europe/Moscow
    env_file:
      - docker/env/.env.dev
    restart: always
    volumes:
      - ./docker/init.sql/:/docker-entrypoint-initdb.d/init.sql
      - msdata:/var/lib/mysql

  nginx:
    container_name: nginx
    working_dir: /app
    image: nginx
    ports:
      - "2567:2567"
    volumes:
      - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
    links:
      - django
    depends_on:
      - django
    
  redis:
    image: redis
    container_name: redis
    env_file:
      - docker/env/.env.dev
    expose:
      - 6379
    volumes:
      - ./docker/redis/data:/data

  celery-worker:
    build:
      context: .
    container_name: celery-worker
    restart: always
    command: celery -A compbatya worker --loglevel=info
    volumes:
      - ./:/app
      - ./media:/app/media
    env_file:
      - docker/env/.env.dev
    depends_on:
      - redis